### ISSUE TITLE
Happner process does not terminate when filename and compactInterval are specified in happn

### ISSUE THREAD

**Issue by cyrussalem** [happner/happner-2#178]
**Required Info**  
- *Priority/Impact:* (H), this will cause all our Travis builds to fail.
- *Assignee:* Simon
- *TR:* 

Below is an example happner config exposing this issue:

```
{
      "happn": {
        "filename": "[Your file path]",
        "defaultRoute": "mem",
        "compactInterval": 5000,
      }
    }
```

I have added a unit test for this here https://github.com/happner/happner-2/tree/bug/issue-178-stuck-process

---
**Updates**
03/05/19-CS: Created

**Comment by cyrussalem** [comment]
@southbite I have added a unit test for this here https://github.com/happner/happner-2/tree/bug/issue-178-stuck-process

**Comment by southbite** [comment]
Hi Cyrus - thanks for this - looks like happn-3 is possibly stopping db compaction, will take a look and revert.

**Comment by southbite** [comment]
Ok, had a look - this may be a misunderstanding - mesh.stop does not cause a process exit, unless configured to do so, ie: mesh.stop({kill:true}) - otherwise we would have tests involving multiple meshes stopping and restarting breaking mocha processes everywhere.

**Comment by southbite** [comment]
imagine an http server killed its host process when you call .close()

**Comment by southbite** [comment]
added the test and updated the stop method in the child process to include kill:true, and the test now passes

**Comment by cyrussalem** [comment]
@southbite but why does the process exit when we do not specify a database file in the config file and also not set kill to true in the stop function?
