### ISSUE TITLE
stopping mesh via CTRL+C (SIGINT) is causing component stopMethod to be called twice

### ISSUE THREAD

**Issue by HaroldStruwig** [happner/happner-2#221]
[TR4248](https://github.com/FieldServer/smc-project-board-issues/issues/408)

**Required Info**  
- *Description:* also for `shutdownMethod`
- *Priority/Impact:* (M), it causes unhandled exceptions since we expect this to only be called once
- *Assignee:* Recommended assignee
- *TR:* Recommended project
- *Dependencies:* none

---
**Updates**

---

**Comment by southbite** [comment]
fixed in release/11.0.1
