### ISSUE TITLE
bug - _ADMIN user password resets to config file value on restart

### ISSUE THREAD

**Issue by JensEggers** [happner/happner-2#38]

**Comment by JensEggers** [comment]
@southbite when moving things to review, please could you point at what to review, e.g. where the fix is

**Comment by JensEggers** [comment]
best is when issues are linked to pull requests by being mentioned in the comments or commit message

**Comment by JensEggers** [comment]
needs more discussion

**Comment by southbite** [comment]
fixed in release 7.1.1
