### ISSUE TITLE
happner-2 quietly fails to start if server port is already in use

### ISSUE THREAD

**Issue by JensEggers** [happner/happner-2#80]
**[TR4127](https://github.com/FieldServer/smc-project-board-issues/issues/185)**

**Comment by southbite** [comment]
this could be because happn-3 waits 20 seconds for the port to open, then fails. So tests that timeout before the 20 seconds would make it seem like this is happening. We could make the wait shorter or add a waiting-for-port event?

**Comment by JensEggers** [comment]
why not fail immediately?

**Comment by southbite** [comment]
This is because the port is not released immediately when the mesh is stopped, it takes a small amount time to do so, so starting up the mesh again on the same port raised errors, I could make this configurable and then default it to an immediate error callback, run the tests and see what happens?

**Comment by JensEggers** [comment]
Yes that sounds good
