### ISSUE TITLE
inexplicable loss of events on single mesh

### ISSUE THREAD

**Issue by southbite** [happner/happner-2#84]
Within the fieldpop project, events between components inexplicably stop firing. I have done some extensive tests but cannot seem to replicate this.
One test remains: to set up to meshes with intercomponent events, then force an endpoint reconnect and check our events still fire, as I can see that old events are disconnected when a reconnect happens. This may or may not have a bearing on intra-mesh component events.

**Comment by JensEggers** [comment]
here's a trace highlighting the likely cause:
```
==================================
removeSubscription path     : /_events/field-pop/server/deviceRegistered/A corp/*
subscriptions: 
  /_events/field-pop/server/deviceRegistered/*
  /_events/field-pop/server/deviceRegistered/A corp/*
  /_events/field-pop/server/deviceStatus/*
  /_events/field-pop/server/deviceStatus/A corp/*
  /_events/field-pop/server/edge/*/data_notification
  /_events/field-pop/server/notifications/*
====================
matching subscriptions: 
  /_events/field-pop/server/deviceRegistered/A corp/*
  /_events/field-pop/server/deviceRegistered/A corp/*
subscriptions after delete: 
  /_events/field-pop/server/deviceRegistered/*
  /_events/field-pop/server/deviceStatus/A corp/*
  /_events/field-pop/server/edge/*/data_notification
  /_events/field-pop/server/notifications/*
```
 You can see that the matching subscription is returned twice in the search result. This leads to the entry at index 1 being removed twice over, which wipes out the next subscription.

**Comment by JensEggers** [comment]
Next steps as discussed with @southbite:
1. make a unit test that reproduces this behaviour.
2. see if the current implementation can be fixed easily, and if yes, do it
3. otherwise wait for the wild-pare upgrade and verify that the test passes then.

**Comment by JensEggers** [comment]
closed long ago by fixing event unsubscribes
