### ISSUE TITLE
"slow leak" and leak detection tests

### ISSUE THREAD

**Issue by southbite** [happner/happner-2#89]

**Comment by JensEggers** [comment]
2 new aspects:
- look for leaks in fieldserver/field-pop (devices/REST)
- look for leaks in fieldserver/fielpop-user-mgr

**Comment by southbite** [comment]
created a leak detection set of scripts, the project is here: https://github.com/FieldServer/fieldpop-memory-profiling
we now need to fill out the activity emulation tests here:
https://github.com/FieldServer/fieldpop-memory-profiling/tree/master/__resources/client/tests
